### PR TITLE
Upgrade workflows to Java 17

### LINKED ISSUE #102: Upgrade workflows to Java 17

### PR DESCRIPTION
**Pull request by jonkoops**
Upgrades all workflows to Java 17, this PR also aligns all versions of `actions/setup-java` to v3.

**Nightly run**: https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/5453516245
**Release run**: https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/5453524431

Closes #102

### CODE REVIEW

**Review by stianst — CHANGES_REQUESTED** [review]
Using `cache: maven` results in caching not only Maven dependencies, but also Keycloak artifacts. It'll basically end up always updating the cache, and could lead to unexpected side-effects, especially for nightlies.

In terms of upgrading to Java 17, there's some issues with that at the moment, haven't had time to look at it, but there's something with the Admin API docs not being generated properly.

**Comment by jsorah** [comment]
> Using `cache: maven` results in caching not only Maven dependencies, but also Keycloak artifacts. It'll basically end up always updating the cache, and could lead to unexpected side-effects, especially for nightlies.
> 
> In terms of upgrading to Java 17, there's some issues with that at the moment, haven't had time to look at it, but there's something with the Admin API docs not being generated properly.

Admin API doc generation should work with Java 17+ at this point now that keycloak/keycloak#20433 is closed

**Comment by rmartinc** [comment]
Just one more comment, the previous week a comment in an issue pointed out that SSSD is not available in the nightly build. This is because it's generated using jdk-11. The current implementation uses the native implementation for unix sockets, which is only available since jdk-16. That jar manages a multi-release. Therefore using a jdk-11 does not compile the needed classes for SSSD. So we need this to have SSSD available.

**Comment by abstractj** [comment]
@jonkoops I noticed the following error, but not sure if it's related with the changes proposed here:

```
Error: fatal: could not read Username for 'https://github.com/': terminal prompts disabled
  The process '/usr/bin/git' failed with exit code 128
```

**Review by abstractj — APPROVED** [review]

**Comment by jonkoops** [comment]
Doesn't seem related to this PR, nighties seem to be alright now, so I think this fix was successful.

**Comment by jonkoops** [comment]
Doesn't seem related to this PR, nighties seem to be alright now, so I think this fix was successful.

**Pull request merged**
