### PR TITLE
Use the "latest" profile for the docs so that it behaves like in KC20

### PR DESCRIPTION
**Pull request by ahus1**
Relates: keycloak/keycloak#19974

### CODE REVIEW

**Comment by BrayanMnz** [comment]
LGTM!

**Comment by stianst** [comment]
Looks like the `latest` has been broken for quite some time. Looking at the archive version for 20 it's marked as the latest:

image

While 18 isn't:

image

Can't quite remember how that used to be done, but I suspect at some point in the past the docs was built twice. Once for the `versioned` link, and another for the `latest` link.

I think it would be better to just drop this for now, and introduce it again once we move to Antora as you suggested in https://github.com/keycloak/keycloak/issues/19974#issuecomment-1527823712

**Comment by ahus1** [comment]
@stianst - thank you for the review. I'll create another PR for the docs in the main repository for that. In the meantime, please merge this PR.

**Comment by ahus1** [comment]
OK, true. The other PR is already available: keycloak/keycloak#20103. Closing this one in favor of the other one.

**Pull request closed without merging**
