### PR TITLE
Build Operator when building the API docs

### PR DESCRIPTION
**Pull request by ahus1**
Closes: #121

### CODE REVIEW

**Comment by ahus1** [comment]
I've tested it locally and it prevents the build from failing. 

This raises the question if the `all` profile should include building the Operator - I'll leave that for a follow-up discussion.

**Review by pskopek — APPROVED** [review]
LGTM

**Comment by stianst** [comment]
Why do we need operator in the api-docs? There's no public APIs in there that folks should be using.

This change would result in publishing the operator jars, which we never have before I believe.

I think the correct fix here is to revert some of the changes in https://github.com/keycloak/keycloak/commit/25548a7ccc65bb7a426f15a95f2472628790147b

**Comment by ahus1** [comment]
@stianst - thank you for this additional context. I've prepared a PR which removes the additional dependencies from the original PR, but keeps the updated structure: https://github.com/keycloak/keycloak/pull/29985

Please review when you have the time. Thanks!

**Pull request closed without merging**
