### PR TITLE
added admin ui to npm

### PR DESCRIPTION
**Pull request by edewit**
Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

### CODE REVIEW

**Comment by edewit** [comment]
did a run can we merge this?

**Comment by jonkoops** [comment]
Can you link the runs you did on the testing repo here?

**Comment by edewit** [comment]
testing run seems to not run: https://github.com/keycloak-rel-testing/keycloak-rel/pull/43

**Comment by edewit** [comment]
https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/9987047936

**Comment by stianst** [comment]
> https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/9987047936

That's a nightly release test, which skips the NPM publishing. Started a test release run here:

https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/9988875160

**Comment by edewit** [comment]
tag is needed when pushing to registry --- does that mean that it's fine?

**Comment by jonkoops** [comment]
> tag is needed when pushing to registry --- does that mean that it's fine?

What do you mean @edewit? Did one of the sample runs fail? If so, could you link them here?

**Comment by edewit** [comment]
@jonkoops have a look at the linked log...

**Comment by edewit** [comment]
@stianst can this be merged now?

**Comment by stianst** [comment]
Running a new test job here https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/10351203651 - hopefully this works now

**Comment by stianst** [comment]
okay, hopefully now it works https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/10352935238

**Pull request merged**
